# Generated by Django 4.2.2 on 2023-06-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_catagory',
            fields=[
                ('pc_name', models.CharField(max_length=100)),
                ('pc_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.IntegerField()),
                ('pdate', models.DateField()),
                ('pc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_catagory')),
            ],
        ),
    ]
